# Generated by Django 4.0.3 on 2022-03-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0003_bodybuild_alter_quljangi_haqida_alter_quljangi_rasm'),
    ]

    operations = [
        migrations.CreateModel(
            name='fitnes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('rasm', models.ImageField(upload_to='media/media/')),
                ('haqida', models.TextField(max_length=1000)),
            ],
        ),
    ]
