# Generated by Django 4.0.3 on 2022-03-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0004_fitnes'),
    ]

    operations = [
        migrations.CreateModel(
            name='OlmosVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('video_url', models.FileField(upload_to='', verbose_name='video')),
            ],
        ),
    ]
