# Generated by Django 4.0.3 on 2022-03-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0006_jamoa_alter_olmosvideo_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='MashqVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='media/media/')),
            ],
        ),
        migrations.AlterField(
            model_name='jamoa',
            name='nomer',
            field=models.CharField(max_length=40),
        ),
    ]
