# Generated by Django 4.0.3 on 2022-03-12 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0008_mashqrasm'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MashqRasm',
            new_name='Video3Etaj',
        ),
    ]
