# Generated by Django 4.0.3 on 2022-03-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0009_rename_mashqrasm_video3etaj'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marosim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='media/media/')),
            ],
        ),
    ]
