# Generated by Django 4.0.3 on 2022-03-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0010_marosim'),
    ]

    operations = [
        migrations.CreateModel(
            name='JamoaOlmos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('rasm', models.ImageField(upload_to='')),
                ('nomer', models.CharField(max_length=40)),
                ('facebook', models.URLField(max_length=1024)),
                ('instagram', models.URLField(max_length=1024)),
                ('telegram', models.URLField(max_length=1024)),
            ],
        ),
        migrations.DeleteModel(
            name='Jamoa',
        ),
    ]
